config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :user
  
  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :password, presence: true, length: { minimum: 3, maximum: 50 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id].present?
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?
    flash[:error] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
  
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  # GET / -> root_path
  def index
    @message = Message.new
    @messages = Message.order('created_at desc').limit(20)
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  # POST /messages
  def create
    @message = current_user.messages.new(message_params)
    mod_message = message_render(@message)
    ActionCable.server.broadcast('chatroom_channel', mod_message: mod_message) if @message.save 
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, except: :destroy
  
  # GET /login (sessions#new)
  def new; end

  # POST /login (sessions#create)
  def create
    user = User.find_by(username: params[:session][:username])
    if user.present? && user.authenticate(params[:session][:password])
      flash[:success] = 'Logged in successfully' 
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = 'Incorrect Username or Password'
      render 'new'
    end
  end

  # DELETE /logout (sessions#destroy)
  def destroy
    session[:current_user_id] = nil
    flash[:success] = 'Logged out successfully' 
    redirect_to root_path
  end

  private

  def logged_in_redirect
    return unless logged_in?
    flash[:error] = 'You are already logged in' 
    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alerts/_alert.html.erb
<% flash.each do |type, message| %>
  <div class="ui <%= type == 'error' ? 'negative' : 'success' %> message">
    <i class="close icon"></i>
    <div class="header">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Message Me
</h2>

<div class="ui grid">

  <div class="twelve wide column">
    <div class="ui fluid card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="chatroom-messages">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with model: @message, url: message_path, class: 'ui reply form', remote: true do |form| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= form.text_field :body, placeholder: 'Enter a message...' %>
              <%= form.button id: 'submit_message_button' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui card chatbox">
      <div class="content">
        <div class="ui fluid inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_navbar.html.erb
<div class="ui inverted small menu">
  <%= link_to 'Chatroom', root_path, class:"item"%>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <% if logged_in? %>
      <div class="ui dropdown item">
        <%= current_user.username %> <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to 'Log Out', logout_path, method: :delete, class:"item"%>
        </div>
      </div>
    <% else %>  
      <div class="item">
        <%= link_to 'Sign in or Sign Up', login_path, class:"ui orange button"%>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= render 'alerts/alert' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em>
        <%= message.user.username %>
      </em>: 
      <%= message.body %>
    </div>
  </div>
</div>